name: sse_gnn
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=mkl
  - absl-py=0.9.0=py38_0
  - appdirs=1.4.3=py_0
  - astunparse=1.6.3=py_0
  - attrs=19.3.0=py_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - blinker=1.4=py38_0
  - brotlipy=0.7.0=py38h7b6447c_1000
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.6.24=0
  - cachetools=4.1.0=py_1
  - certifi=2020.6.20=py38_0
  - cffi=1.14.0=py38he30daa8_1
  - chardet=3.0.4=py38_1003
  - click=7.1.2=py_0
  - cryptography=2.9.2=py38h1ba5d50_0
  - dbus=1.13.16=hb2f20db_0
  - expat=2.2.9=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - gast=0.3.3=py_0
  - git=2.23.0=pl526hacde149_0
  - glib=2.65.0=h3eb4bd4_0
  - google-auth=1.14.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.27.2=py38hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - h5py=2.10.0=py38h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - intel-openmp=2020.1=217
  - joblib=0.15.1=py_0
  - jpeg=9b=h024ee3a_2
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py38hfd86e86_0
  - krb5=1.18.2=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.71.0=h20c2e04_0
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.12.3=hd408876_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - markdown=3.1.1=py38_0
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py38hef1b27d_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.1.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - mypy=0.770=py_0
  - mypy_extensions=0.4.3=py38_0
  - ncurses=6.2=he6710b0_1
  - numpy-base=1.18.5=py38hde5b4d6_0
  - oauthlib=3.1.0=py_0
  - openssl=1.1.1g=h7b6447c_0
  - opt_einsum=3.1.0=py_0
  - pandas=1.0.5=py38h0573a6f_0
  - pathspec=0.7.0=py_0
  - pcre=8.44=he6710b0_0
  - perl=5.26.2=h14c3975_0
  - pip=20.1.1=py38_1
  - protobuf=3.12.3=py38he6710b0_0
  - psutil=5.7.0=py38h7b6447c_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pydocstyle=5.0.2=py_0
  - pyjwt=1.7.1=py38_0
  - pyopenssl=19.1.0=py38_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - pysocks=1.7.1=py38_0
  - python=3.8.3=hcff3b4d_0
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - regex=2020.6.8=py38h7b6447c_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - scikit-learn=0.23.1=py38h423224d_0
  - scipy=1.5.0=py38h0b6359f_0
  - seaborn=0.10.1=py_0
  - setuptools=47.3.1=py38_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py_0
  - snowballstemmer=2.0.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.2.0=mkl_py38h6d3daf0_0
  - tensorflow-base=2.2.0=mkl_py38h5059a2d_0
  - tensorflow-estimator=2.2.0=pyh208ff02_0
  - termcolor=1.1.0=py38_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - tornado=6.0.4=py38h7b6447c_1
  - typed-ast=1.4.1=py38h7b6447c_0
  - typing_extensions=3.7.4.2=py_0
  - urllib3=1.25.9=py_0
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py38_0
  - wrapt=1.12.1=py38h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - ase==3.19.1
    - cloudpickle==1.5.0
    - cycler==0.10.0
    - decorator==4.4.2
    - dill==0.3.2
    - future==0.18.2
    - jsonschema==3.2.0
    - matminer==0.6.3
    - megnet==1.1.8
    - monty==3.0.2
    - mpmath==1.1.0
    - multiprocess==0.70.10
    - networkx==2.4
    - numpy==1.19.0
    - packaging==20.4
    - palettable==3.3.0
    - pathos==0.2.6
    - pint==0.13
    - plotly==4.8.1
    - pox==0.2.8
    - ppft==1.6.6.2
    - pymatgen==2020.6.8
    - pymongo==3.10.1
    - pyrsistent==0.16.0
    - retrying==1.3.3
    - ruamel-yaml==0.16.10
    - ruamel-yaml-clib==0.2.0
    - smact==2.2
    - spglib==1.15.1
    - sympy==1.6
    - tabulate==0.8.7
    - tensorflow-probability==0.10.0
    - tqdm==4.46.1
prefix: /home/alex/miniconda3/envs/sse_gnn

